com.dwarfeng.logicengine.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.logicengine.jdbc.url=\
  jdbc:mysql://your-host-here:3306/logic_engine?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.logicengine.jdbc.username=root
com.dwarfeng.logicengine.jdbc.password=your-password-here
com.dwarfeng.logicengine.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
